title: Martin Cepeda
description: A personal website
social_link: instagram
social_username: eme.cpa
github_repo: athena
github_username: cepedus
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /cepedus
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
